[package]
name = "hat"

authors.workspace = true

edition.workspace = true
version.workspace = true

description.workspace = true
# keywords.workspace = true
# categories.workspace = true

# homepage.workspace = true
repository.workspace = true
# documentation.workspace = true
readme.workspace = true
license-file.workspace = true

# include.workspace = true
# exclude.workspace = true

rust-version.workspace = true

[[bin]]
name = "hat"
required-features = ["default"]

[features]
default = ["clap", "tokio", "tracing"]

clap = ["clap/std", "clap/derive", "clap/help"]
tokio = ["tokio/rt-multi-thread"]
tracing = ["tracing-subscriber/fmt"]

[badges]
maintenance = { status = "actively-developed" }

[lints]
workspace = true

[dependencies]
dene = { workspace = true }
qalam = { workspace = true }

anyhow = { workspace = true }
base64 = { workspace = true }
clap = { workspace = true }
time-format = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[workspace]
members = ["dene", "qalam"]
resolver = "3"

[workspace.dependencies]
dene = { path = "dene" }
qalam = { path = "qalam" }

anyhow = { version = "1.0.102", default-features = false }
base64 = { version = "0.22.1", default-features = false }
clap = { version = "4.6.0", default-features = false }
time-format = { version = "1.2.2", default-features = false }
tokio = { version = "1.52.1", default-features = false }
tracing = { version = "0.1.44", default-features = false }
tracing-subscriber = { version = "0.3.23", default-features = false }

[workspace.package]
authors = ["Alibek<freed.alibek@gmail.com>"]

edition = "2024"
version = "0.1.0"

description = ""
# keywords = []
# categories = []

# homepage = ""
repository = "https://github.com/lolp1ke/qara"
# documentation = ""
readme = "README.md"
license-file = "LICENSE-APACHE"

# include = []
# exclude = []

rust-version = "1.94.0"

[workspace.lints.rust]
unsafe_code = "warn"

[workspace.lints.clippy]
allow_attributes = "warn"
allow_attributes_without_reason = "warn"
