# SPDX-License-Identifier: Apache-2.0

[[keybindings]]
[keybindings.bindings]
"ctrl-q" = "Quit"

[[keybindings]]
context = "input"
[keybindings.bindings]
"left" = "CursorLeft"
"right" = "CursorRight"
"up" = "CursorUp"
"down" = "CursorDown"
"delete" = "DeleteAtCursorPos"
"shift-return" = "InsertNewLineAtCursorPos"
"space" = "InsertSpaceAtCursorPos"
"return" = "SendMessage"
